PUT http://localhost:8080/events/5
content-type: application/json

{
  "name": "Updated test event",
  "description": "A test event",
  "location": "UPDATED test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}